backend:
  name: test-repo #git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: dyffwww1m
#     api_key: 573263727254786
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "cms-content/home.md"
        fields:
          - label: "Home Slider"
            name: "homeSlider"
            widget: list
            fields:
              - { label: "Header", name: "header", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Button Text", name: "buttonText", widget: "string" }
              - { label: "Button Link", name: "buttonLink", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
      - label: "About"
        name: "about"
        file: "cms-content/about.md"
        fields:
          - label: "About Section"
            name: "aboutSection"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - label: "Bullet Points"
                name: "bulletPoints"
                widget: list
                field:
                  {
                    label: "Bullet Point",
                    name: "bulletPoint",
                    widget: "string",
                  }
      - label: "Services"
        name: services
        file: cms-content/services.md
        fields:
          - label: "Our Services"
            name: servicesSection
            widget: list
            fields:
              - { label: "Header", name: "header", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Button Link", name: "buttonLink", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
