import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HomeSlideWheel from "../components/home-slider/home-slider.component";
import { Efect, Efect1, Efect2 } from "../styles/effect.styles";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        ></link>
      </Head>

      <div>
        <Efect />
        <Efect1 />
        <Efect2 />

        <section className="jumbotron jumbomain">
          <HomeSlideWheel />
        </section>
      </div>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </>
  );
};

export default Home;
